### ISSUE TITLE
Regarding hosting

### ISSUE THREAD

**Issue by hs-07** [smily31/Analog-clock#1]
hey!!
Have you hosted this application?
If yes, so please please mention the link of that in description.

**Comment by smily31** [comment]
Yes I hosted that but there is some issue while hosting .
I'll try to again host it on other platform and then get back to you

**Comment by hs-07** [comment]
On which platform did you hosted it?
May I help you in any sort of help?

**Comment by smily31** [comment]
On GitHub itself And on vercel too

**Comment by hs-07** [comment]
so what is the problem you are facing??

**Comment by smily31** [comment]
its saying that activity log is not present at that server

**Comment by hs-07** [comment]
achaa ohky....
what is the name you have set for main html landing page.... 
make it index.html....
